version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/discord-bot
hooks:
  BeforeInstall:
    - location: scripts/install_discordpy
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_bot
      timeout: 300
      runas: ec2-user
